export const SET_EMPLOYEES = "SET_EMPLOYEES" // replace whole data
export const FORCE_FETCH_EMPLOYEES = "FORCE_FETCH_EMPLOYEES"
export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES"
export const GET_EMPLOYEES = "GET_EMPLOYEES"
export const ADD_EMPLOYEE = "ADD_EMPLOYEE"
export const DEL_EMPLOYEE = "DEL_EMPLOYEE"
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE"